name: venv
channels:
  - defaults
dependencies:
  - wincertstore
  - parso
  - pyzmq
  - pip
  - pywin32
  - six
  - vs2015_runtime
  - prompt-toolkit
  - setuptools
  - wheel
  - python-dateutil
  - wcwidth
  - packaging
  - backcall
  - nest-asyncio
  - traitlets
  - executing
  - certifi
  - tornado
  - libsodium
  - pandas
  - entrypoints
  - sqlite
  - python=3.8
  - black
  - psutil
  - numpy
  - zeromq
  - pure_eval
  - ca-certificates
  - stack_data
  - jupyter_core
  - ipykernel
  - vc
  - decorator
  - ipython
  - asttokens
  - debugpy
  - matplotlib-inline
  - colorama
  - jedi
  - jupyter_client
  - openssl
  - pygments
  - pickleshare
  - pyparsing
  - pycrypto
